rootProject.name = "CSPanelService"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    includeBuild("convention-plugins/panel-build")
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

include("core")
include("features")
include("features:selenium")
include("features:selenium:data")
include("features:selenium:domain")
include("features:steam")
include("features:steam:data")
include("features:steam:di")
include("features:steam:domain")
include("core:system")
include("features:remote")
include("features:remote:domain")
include("features:remote:di")
include("features:remote:data")
include("remote")
include("features:cs2")
include("features:cs2:data")
include("features:cs2:di")
include("features:cs2:domain")
include("features:info")
include("features:info:data")
include("features:info:domain")
include("features:info:di")
include("core:network")
include("features:market")
include("features:market:data")
include("features:market:di")
include("features:market:domain")
include("features:database")
include("features:database:data")
include("features:database:domain")
include("features:database:di")
include("shared")
include("di")
include("shared:market_database")
include("features:float")
include("features:float:di")
include("features:float:data")
include("features:float:domain")
include("features:pulse")
include("features:pulse:data")
include("features:pulse:domain")
include("features:pulse:di")
include("features:datastore")
include("features:datastore:di")
include("features:datastore:data")
include("features:datastore:domain")
include("trade")
include("features:pulse:presentation")
include("features:files")
include("features:files:data")
include("features:files:di")
include("features:files:domain")
include("features:steam:presentation")
include("features:lisskins")
include("features:lisskins:data")
include("features:lisskins:di")
include("features:lisskins:domain")
include("features:trade")
include("features:trade:di")
include("features:trade:domain")
include("features:trade:presentation")
include("core:cache")
include("core:database")
include("features:market_csgo")
include("features:market_csgo:di")
include("features:market_csgo:data")
include("features:market_csgo:domain")